**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [ ]:
import numpy as np

array = np.random.randint(1, 101, 50)
print(array)

print(f"Média: {np.mean(array)}")
print(f"Média: {np.median(array)}")
print(f"Média: {np.std(array)}")
print(f"Média: {np.max(array)}")
print(f"Média: {np.min(array)}")

[23 42 90 33 27 28 17  1 50 97 86 78  9 88 30 32 91 15 68 83 38 68 39 14
 89 77 41 85  2 99 24 71 84 77 89 52 22 47 23 98 62 61 50 23 56 70 96 62
 81  4]
Média: 53.84
Média: 54.0
Média: 29.72228793346838
Média: 99
Média: 1


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [ ]:
import numpy as np

a = np.random.randint(1, 11, (3, 3))
b = np.random.randint(1, 11, (3, 3))
print(a)
print(b)

print("Adição: ")
print(a + b)

print ("Subtração: ")
print(a-b)

print("Multiplicação:")
print(np.multiply(a, b))

print("Divisão: ")
print(a/b)



[[ 9 10  5]
 [ 3  5  4]
 [ 7  4  3]]
[[ 7  3  3]
 [10  1 10]
 [10  9  7]]
Adição: 
[[16 13  8]
 [13  6 14]
 [17 13 10]]
Subtração: 
[[ 2  7  2]
 [-7  4 -6]
 [-3 -5 -4]]
Multiplicação:
[[63 30 15]
 [30  5 40]
 [70 36 21]]
Divisão: 
[[1.28571429 3.33333333 1.66666667]
 [0.3        5.         0.4       ]
 [0.7        0.44444444 0.42857143]]


**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [ ]:
import numpy as np

matriz = np.random.randint(1, 21, (4, 4))
print (matriz)

print(f"Soma das Linhas: {np.sum(matriz, axis=1)}")
print(f"Soma das Colunas: {np.sum(matriz, axis=0)}")

[[10 15 18  2]
 [10 20 15 19]
 [ 5 11 11  7]
 [ 7  3 10 11]]
Soma das Linhas: [45 64 34 31]
Soma das Linhas: [32 49 54 39]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [1]:
import numpy as np

array = np.random.randint(0, 51, 30)
array

print(array[array > 25])

[29 34 44 37 42 40 48 35 48 40 32 40 48 31 46 29 32]


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

In [4]:
import numpy as np 

matriz = np.random.randint(1,11 (3,3,3,))

print(matriz)
print(matriz.sum())
print(matriz.cumsum())

<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_7247/3510194541.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  matriz = np.random.randint(1,11 (3,3,3,))


TypeError: 'int' object is not callable